/* Valuation of Firms */

scalar commercialPaper = 4996
scalar termDebt = 8773 + 98667
scalar CFoperating = 80674
scalar CFinvesting = -9742     
scalar interest = 3002
scalar shares = 17352.119
scalar growth5years = 0.1469
scalar growthInflation = 0.025     // assumes no growth in real terms
scalar beta = 1.25
scalar RFrate = 0.0246
scalar yieldDebtFirm = 0.028     // current interest rate on longest-term debt
scalar indexW1970 = 1
scalar indexW2020 = 185.45

scalar indexYears = 2020 - 1970    // present value is at time 0
scalar incomeBeforeTax = 67091    // from 10-K Income Statement
scalar tax = 9680    // from 10-K Income Statement
scalar taxRate = tax / incomeBeforeTax
scalar price = 120    // from yahoo finance

/******************************************************************************/
/**  Estimate cash flows to the firm generated by business in 2020 (Year 0)  **/
/******************************************************************************/

scalar CFfirm0 = CFoperating + interest + CFinvesting
scalar list CFfirm0

forvalues i=1/5 {
local j = `i' - 1
scalar CFfirm`i' = CFfirm`j' * (1 + growth5years)
scalar list CFfirm`i'
}

/* we need only the first five cash flows as starting with CFF5 we have a 
constant growth perpetuity */

/******************************************************************************/
/*************    Estimate appropriate discount rate: WACC     ****************/
/******************************************************************************/

/****   Estimate the cost of equity using CAPM   ****/

* Estimate expected market return (using historical data)
*FV = PV * (1+i)^t
scalar marketReturn = (returnW2020 / returnW1970)^(1/indexYears) - 1
scalar list marketReturn

* Use CAPM

scalar returnEqFirm = RFrate + beta * (marketReturn - RFrate)
scalar list returnEqFirm

/****   Estimate market value of equity and book value of debt   ****/
/****   Market value of debt would be better but we do not have it   ****/

scalar MVequity = shares * price
scalar list MVequity
scalar BVdebt = commercialPaper + termDebt
scalar list BVdebt

/****   Estimate WACC   ****/
/****   If the firm has preferred stock, include it  ****/

scalar WACC = (MVequity*returnEqFirm + BVdebt*yieldDebtFirm*(1 - taxRate))  ///
   / (MVequity + BVdebt)
scalar list WACC

/******************************************************************************/
/**********    Estimate the present value of future cash flows     ************/
/******************************************************************************/

/****   Estimate the value of constant growth perpetuity one year   ****/
/****   before it starts   ****/

scalar PV4CGP = CFfirm5 / (WACC - growthInflation)
scalar list PV4CGP

/****   Estimate the value of the firm   ****/
/****   Estimate the present value of future cash flows   ****/

scalar valueFirm = CFfirm1 / (1 + WACC)^1 + CFfirm2 / (1 + WACC)^2 +   ///
   CFfirm3 / (1 + WACC)^3 + CFfirm4 / (1 + WACC)^4 + PV4CGP / (1 + WACC)^4 
scalar list valueFirm

/******************************************************************************/
/**********    Estimate the value of one share of common stock,     ***********/
/**********         estimate overpricing/underpricing, and          ***********/
/**********     make decision about buy/hold/sell recommendation    ***********/
/******************************************************************************/

/****   Estimate the value of the firm equity  ****/
/****   Market value of debt would be better but we do not have it   ****/
/****   If the firm has preferred stock, subtract its value   ****/

scalar valueFirmEq = valueFirm - BVdebt 
scalar list valueFirmEq

/****   Estimate the value of one common share  ****/

scalar valueShare = valueFirmEq / shares 
scalar list valueShare

/****   Overpricing/underpricing as the percent of estimated share value   ****/

scalar overpricing = (price - valueShare) / valueShare 
scalar list overpricing

/****   Hold if overpricing/underpricing from -40% to 40%    ****/
/****   This is not a precise rule, but we will use it in class    ****/

* Sell as overpriced by more than 40%

