* CW_Compustat_20210221

* global data_st "/Users/macbook2019/Documents/Data_Programs/DataStata"
/* this statement creates a global macro; differently from local macros,
Stata remembers global macros until they are deleted or Stata is closed;
Whenever I will write $data_st or ${data_st}, Stata will substitute the 
text between quotation marks */
pwd
global FIL341 ///
"C:\Users\Ranst\OneDrive\Desktop\Stata"

clear
use ${FIL341}/Comp20.dta
br

summarize at ceq dcvt dd1 dd2 dlc dltt mkvalt ebit ppent ///
pstk sale, detail

drop if at == 0    // drops all observations (firm years) when at is 0
drop un    //  drops variable un

generate double dlc_dltt_at = (dlc+dltt)/at
br    //  opens the dataset we are working on
label variable dlc_dltt_at "Book Leverage"
* creates a label for a variable
summarize dlc_dltt_at, detail
help summarize
scalar p50dlc_dltt_at = r(p50)
* saves one number that was generated by summarize
scalar list p50dlc_dltt_at

generate double MVat = at - ceq + mkvalt
generate double dlc_dltt_MVat = (dlc+dltt)/MVat
generate double ebit_at = ebit / at
generate double logAt = log(at+1)
/* this works best for variables that have values above 0 like assets
(we deleted observations with 0s) and variables where increases in value
matter (large firms are different from small firms), however ones firm is
large increases do not matter as much; it is common to do this for assets
when we use them in regressions */

summarize dlc_dltt_MVat, detail

reg dlc_dltt_at logAt ebit_at
reg dlc_dltt_at logAt ebit_at, cluster(gvkey)
/* added ", cluster(gvkey)" because we have many observations for the same firm
(the same gvkey); we have annual data starting in 2000 */


